<p><a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>

Guestbook Entries: <br />
<TABLE>
	<tr>
		<td>Festival Name</td>
		<td>City</td>
		<td>Edition</td>
	</tr>
	<?php foreach ($this->entries as $entry): ?>
	<tr>
    <td><?php echo $this->escape($entry->email) ?></td>
    <td><?php echo $this->escape($entry->comment) ?></td>
    </tr>
    <?php endforeach ?>
</TABLE>
    

